- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  secretEnv: ['GIT_ACCESS_TOKEN']
  args:
  - '-c'
  - |
    git clone https://cat1544:$$GIT_ACCESS_TOKEN@github.com/cat1544/ING.git -b main
    echo "Updating image tag version ..."
    cd ING
    sed -i "s|image: .*|image: asia-northeast3-docker.pkg.dev/${PROJECT_ID}/gcf-artifacts/my-image:$SHORT_SHA|" GKE/cluster/argocd/test.yaml
    echo "Pushing changes to k8s manifest repo ..."
    git config --global user.name "cat1544"
    git config --global user.email "dbstl159@naver.com"
    git add -A
    git commit -m "[Cloud Builder] Updated image tag asia-docker.pkg.dev/$PROJECT_ID/gcf-artifacts/my-image:$SHORT_SHA from commit ${COMMIT_SHA}"
    git push https://cat1544:$$GIT_ACCESS_TOKEN@github.com/cat1544/my-image.git -b main
availableSecrets:
  secretManager:
  - versionName: projects/726340762673/secrets/GIT_ACCESS_TOKEN/versions/latest
    env: 'GIT_ACCESS_TOKEN'