steps:
  # 1. Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/gcf-artifacts/my-image/frontend:$SHORT_SHA'
      - './src/frontend/.'

  # 4. Docker Run for testing
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '--rm'
      - '-d'
      - '-p'
      - '8080:8080'
      - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/gcf-artifacts/my-image/frontend:$SHORT_SHA'

  # 5. Test the service using curl
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        sleep 10
        RESPONSE=$(curl -i http://localhost:8080 | grep HTTP | cut -d' ' -f2)
        if [ "200" != "$RESPONSE" ]; then
          echo "Received unexpected response code: $RESPONSE"
          exit 1
        else
          echo "Received expected response code: 200"
        fi

  # 6. Push to GCR if the test succeeds
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/gcf-artifacts/my-image/frontend:$SHORT_SHA'

  # 3. Updated image tag
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    secretEnv: ['GIT_ACCESS_TOKEN']
    args:
      - '-c'
      - |
        git clone https://$_USER_NAME:$$GIT_ACCESS_TOKEN@github.com/$_USER_NAME/ING_k8s.git -b main
        echo "Updating image tag version ..."
        cd ING_k8s
        sed -i '/name: frontend/,/image:/ s|image: .*|image: asia-northeast3-docker.pkg.dev/${PROJECT_ID}/gcf-artifacts/my-image/frontend:'$SHORT_SHA'|' GKE/cluster/app/boutique.yaml
        echo "Pushing changes to k8s manifest repo ..."
        git config --global user.name "$_USER_NAME"
        git config --global user.email "$_USER_EMAIL"
        git add GKE/cluster/app/boutique.yaml
        git commit -m "[Cloud Builder] Updated image tag asia-docker.pkg.dev/$PROJECT_ID/gcf-artifacts/my-image/frontend:$SHORT_SHA from commit ${COMMIT_SHA}"
        git push https://$_USER_NAME:$$GIT_ACCESS_TOKEN@github.com/$_USER_NAME/ING_k8s main

availableSecrets:
  secretManager:
    - versionName: projects/726340762673/secrets/GIT_ACCESS_TOKEN/versions/1
      env: 'GIT_ACCESS_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY
