steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/gcf-artifacts/my-image:${SHORT_SHA}',
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/gcf-artifacts/my-image:${SHORT_SHA}']

  # Change manifests images version
  - name: 'gcr.io/cloud-builders/sed'
    args: ['-i', 's|asia-northeast3-docker.pkg.dev/${PROJECT_ID}/gcf-artifacts/my-image:latest|asia-northeast3-docker.pkg.dev/${PROJECT_ID}/gcf-artifacts/my-image:${SHORT_SHA}|', 'k8s-manifests/test.yaml']

substitutions:
  _OLD_VERSION: 'latest'  # This can be changed as needed
  _VERSION: '${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
