apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webfront
  template:  # 이 부분이 spec 아래로 옮겨져야 합니다.
    metadata:
      labels:
        app: webfront
    spec:
      containers:
      - image: asia-northeast3-docker.pkg.dev/protean-blend-398805/gcf-artifacts/my-image:latests
        name: webfront-container
        ports:
        - containerPort: 80